name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # دریافت پروژه
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: stable
          cache: true

      # نمایش نسخه‌ها برای بررسی
      - name: Flutter Doctor
        run: flutter doctor -v

      # پاک کردن فایل‌های قبلی
      - name: Flutter Clean
        run: flutter clean

      # دریافت پکیج‌ها
      - name: Flutter Pub Get
        run: flutter pub get

      # ساخت APK
      - name: Build Release APK
        run: flutter build apk --release

      # قرار دادن APK در Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: delivery-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error